name: Publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      MASTODON_URL: ${{secrets.MASTODON_URL}}
      MASTODON_TOKEN: ${{secrets.MASTODON_TOKEN}}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn

      - run: yarn install --frozen-lockfiles
      - run: yarn test
      - run: yarn build
      - run: yarn run semantic-release
